FROM nvidia/cuda:10.2-cudnn7-devel-ubuntu18.04 AS BUILD

LABEL maintainer="metya"

ARG CONDA_DIR=/opt/conda

# Instal basic utilities
RUN apt update && \
    apt install -y --no-install-recommends git wget unzip bzip2 build-essential ca-certificates && \
    apt autoremove && \
    apt clean && \
    rm -rf /var/lib/apt/lists /var/cache/apt/archives

# Install miniconda
ENV PATH $CONDA_DIR/bin:$PATH
RUN wget --quiet https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O /tmp/miniconda.sh && \
    echo 'export PATH=$CONDA_DIR/bin:$PATH' > /etc/profile.d/conda.sh && \
    /bin/bash /tmp/miniconda.sh -b -p $CONDA_DIR && \
    apt autoremove && \
    apt clean && \
    rm -rf /tmp/* && \
    rm -rf /var/lib/apt/lists /var/cache/apt/archives

RUN conda install -y pytorch -c pytorch && \
    conda clean -ay

# Runtime image
FROM nvidia/cuda:10.2-base-ubuntu18.04

ARG CONDA_DIR=/opt/conda
ARG USERNAME=docker
ARG USERID=1000

# Instal basic utilities
RUN apt update && \
    apt install -y --no-install-recommends git wget unzip bzip2 sudo p7zip && \
    apt autoremove && \
    apt clean && \
    rm -rf 

ENV PATH $CONDA_DIR/bin:$PATH
ENV CUDA_HOME=/usr/local/cuda
ENV CUDA_ROOT=$CUDA_HOME
ENV PATH=$PATH:$CUDA_ROOT/bin:$HOME/bin
ENV LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$CUDA_ROOT/lib64

RUN mkdir -p /opt/conda/

# Create the user
RUN useradd --create-home -s /bin/bash --no-user-group -u $USERID $USERNAME && \
    chown $USERNAME $CONDA_DIR -R && \
    adduser $USERNAME sudo && \
    echo "$USERNAME ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
USER $USERNAME
WORKDIR /home/$USERNAME

COPY --chown=1000 --from=build /opt/conda/. $CONDA_DIR
